export const PHONES_PAGE = "PHONES_PAGE";
export const PHONES_FETCH = "PHONES_FETCH";
export const PHONES_FETCH_SUCCESS = "PHONES_FETCH_SUCCESS";
export const PHONES_FETCH_ERROR = "PHONES_FETCH_ERROR";
export const PHONES_SELECT_ITEM = "PHONES_SELECT_ITEM";